# Generated by Django 4.1.2 on 2022-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fooddb123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('add', models.CharField(max_length=40)),
                ('food_typeq', models.CharField(choices=[('veg', 'VEG'), ('non-veg', 'NON-VEG'), ('both', 'BOTH')], max_length=10, null=True)),
            ],
        ),
    ]
