# Generated by Django 3.0.5 on 2022-11-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_rename_food_typeq_fooddb123_food_type_fooddb123_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddb123',
            old_name='add',
            new_name='address',
        ),
    ]
